version: '3.8'
services:
  mongodb_todo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - ${STREAMING_MONGO_PORT:-27017}:${MONGO_PORT}
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: